trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: 'src/SIPSorcery.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  framework: 'netcoreapp3.0'

steps:

# If other dotnet SDK versions are required.
#- task: UseDotNet@2
#  inputs:
#    version: '3.0.x'

#- task: UseDotNet@2
#  inputs:
#    version: '2.2.x'
#    packageType: runtime

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(solution)'
        
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --framework=$(framework)' # Update this to match your need

# ...
# do this after other tasks such as building
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'test/SIPSorcery.csproj'
    arguments: '--configuration $(buildConfiguration) --framework=(framework) --filter "Category!=IPv6"'